config/routes.rb
PercentTime::Application.routes.draw do
  resources :percentervals

end

app/models/percenterval.rb
class Percenterval < ActiveRecord::Base
  attr_accessible :date, :hours, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/percentervals_controller.rb
class PercentervalsController < ApplicationController
  # GET /percentervals
  # GET /percentervals.json
  def index
    @percentervals = Percenterval.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @percentervals }
    end
  end

  # GET /percentervals/1
  # GET /percentervals/1.json
  def show
    @percenterval = Percenterval.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @percenterval }
    end
  end

  # GET /percentervals/new
  # GET /percentervals/new.json
  def new
    @percenterval = Percenterval.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @percenterval }
    end
  end

  # GET /percentervals/1/edit
  def edit
    @percenterval = Percenterval.find(params[:id])
  end

  # POST /percentervals
  # POST /percentervals.json
  def create
    @percenterval = Percenterval.new(params[:percenterval])

    respond_to do |format|
      if @percenterval.save
        format.html { redirect_to @percenterval, notice: 'Percenterval was successfully created.' }
        format.json { render json: @percenterval, status: :created, location: @percenterval }
      else
        format.html { render action: "new" }
        format.json { render json: @percenterval.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /percentervals/1
  # PUT /percentervals/1.json
  def update
    @percenterval = Percenterval.find(params[:id])

    respond_to do |format|
      if @percenterval.update_attributes(params[:percenterval])
        format.html { redirect_to @percenterval, notice: 'Percenterval was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @percenterval.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /percentervals/1
  # DELETE /percentervals/1.json
  def destroy
    @percenterval = Percenterval.find(params[:id])
    @percenterval.destroy

    respond_to do |format|
      format.html { redirect_to percentervals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/percentervals_helper.rb
module PercentervalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PercentTime</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/percentervals/_form.html.erb
<%= form_for(@percenterval) do |f| %>
  <% if @percenterval.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@percenterval.errors.count, "error") %> prohibited this percenterval from being saved:</h2>

      <ul>
      <% @percenterval.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/percentervals/edit.html.erb
<h1>Editing percenterval</h1>

<%= render 'form' %>

<%= link_to 'Show', @percenterval %> |
<%= link_to 'Back', percentervals_path %>

app/views/percentervals/index.html.erb
<h1>Listing percentervals</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th>Hours</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @percentervals.each do |percenterval| %>
  <tr>
    <td><%= percenterval.date %></td>
    <td><%= percenterval.name %></td>
    <td><%= percenterval.hours %></td>
    <td><%= link_to 'Show', percenterval %></td>
    <td><%= link_to 'Edit', edit_percenterval_path(percenterval) %></td>
    <td><%= link_to 'Destroy', percenterval, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Percenterval', new_percenterval_path %>

app/views/percentervals/new.html.erb
<h1>New percenterval</h1>

<%= render 'form' %>

<%= link_to 'Back', percentervals_path %>

app/views/percentervals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @percenterval.date %>
</p>

<p>
  <b>Name:</b>
  <%= @percenterval.name %>
</p>

<p>
  <b>Hours:</b>
  <%= @percenterval.hours %>
</p>


<%= link_to 'Edit', edit_percenterval_path(@percenterval) %> |
<%= link_to 'Back', percentervals_path %>